repxp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import handler400, handler403, handler404, handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("site_web.urls")),
    path('select2/', include('django_select2.urls'))
]

handler400 = "site_web.views.error_400"
handler403 = "site_web.views.error_403"
handler404 = "site_web.views.error_404"
handler500 = "site_web.views.error_500"

site_web/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('exercices/new/', views.creer_exercice, name='creer_exercice'),
    path('exercices/review', views.review, name='review'),
    path('exercices/bank', views.bank, name='bank'),
    path('exercices/proposer', views.proposer_exercice, name='proposer_exercice'),
    path('workouts/new', views.new_workout, name='new_workout'),
    path('workouts/edit/<int:workout_id>/', views.edit_workout, name='edit_workout'),
    path('workouts/', views.my_workouts, name='my_workouts'),
    path('workouts/delete/<int:workout_id>/', views.delete_workout, name='delete_workout'),
    path('workouts/complete/<int:workout_id>/', views.complete_workout, name='complete_workout'),
    path('signup/', views.register, name='signup'),
    path('accounts/signin', views.connexion, name='signin'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('profil/', views.profile, name="profile"),
    path("profil/<int:user_id>/", views.view_other_user_profile, name="view_other_user_profile"),
    path('profile/equiper_badge/<int:badge_id>/<int:slot>/', views.equiper_badge, name='equiper_badge'),
    path('users/', views.user_search, name='user_search'),
    path('profile/', views.profile, name="profile"),
    path('profile/edit/', views.edit_profile, name="edit_profile"),
    path('users/', views.user_search, name='user_search'),
    path('badges/create/', views.create_badge, name='create_badge'),
    path('badges/', views.badge_list, name='badge_list'),
    path('defis/create/', views.create_defi, name='create_defi'),
    path("ajax/statistiques/", views.ajax_statistiques, name="ajax_statistiques"),
    path("ajax/check_email/", views.check_email, name="check_email")
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

site_web/models.py
"""Modèles pour la base de données"""

from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinLengthValidator, MaxLengthValidator
from django.utils import timezone
from django.utils.text import slugify
from django.core.exceptions import ValidationError
from django.conf import settings
from dateutil.relativedelta import relativedelta
from cloudinary.models import CloudinaryField


# Create your models here.
class Sexe(models.TextChoices):
    """Modèle des sexes"""
    MASCULIN = "M", "Masculin"
    FEMININ = "F", "Féminin"


class User(AbstractUser):
    """Modèle des utilisateurs"""

    avatar = CloudinaryField(
        'image',
        null=True,
        blank=True
    )

    date_naissance = models.DateField(
        verbose_name="Date de naissance",
        null=True,
        blank=True,
    )

    sexe = models.CharField(
        max_length=1,
        choices=Sexe.choices,
        default=Sexe.MASCULIN,
        null=True,
        blank=True,
    )

    taille = models.DecimalField(
        max_digits=3,
        decimal_places=2,
        null=True,
        blank=True,
        verbose_name="Taille de l'utilisateur"
    )

    poids = models.DecimalField(
        max_digits=4,
        decimal_places=1,
        null=True,
        blank=True,
        verbose_name="Poids de l'utilisateur"
    )

    class Meta:
        """Classe meta des utilisateurs"""
        verbose_name = "Utilisateur"
        verbose_name_plural = "Utilisateurs"
        ordering = ["id"]

    def __str__(self):
        return f"{self.username}"

    def clean(self):
        if self.date_naissance:
            today = timezone.now().date()
            min_birthdate = today - relativedelta(years=15)

            if self.date_naissance > min_birthdate:
                raise ValidationError({
                    'date_naissance': 'Vous devez avoir au moins 15 ans pour vous inscrire.'
                })

        if self.poids:
            if self.poids <= 0:
                raise ValidationError({'poids': "Le poids doit être supérieure à 0."})

        if self.taille:
            if self.taille <= 0:
                raise ValidationError({'taille': "La taille doit être supérieure à 0."})

    def save(self, *args, **kwargs):
        self.full_clean()
        super().save(*args, **kwargs)

class GroupeMusculaire(models.Model):
    """Modèle des groupes musculaires"""

    nom = models.CharField(
        max_length=50,
        blank=False,
        verbose_name="Nom du groupe musculaire",
        unique=True,
    )

    class Meta:
        """Classe meta des groupes musculaires"""
        verbose_name = "Groupe musculaire"
        verbose_name_plural = "Groupes musculaires"
        ordering = ["nom"]

    def __str__(self):
        return f"{self.nom}"


class Exercice(models.Model):
    """Modèle des exercices"""

    nom = models.CharField(
        max_length=100,
        blank=False,
        verbose_name="Nom de l'exercice",
        unique=True,
    )

    groupe_musculaire = models.ForeignKey(
        GroupeMusculaire,
        on_delete=models.SET_NULL,
        related_name="exercices",
        verbose_name="Groupe musculaire",
        null=True,
    )

    series_sugg = models.IntegerField(
        blank=False,
        verbose_name="Séries recommandées"
    )

    reps_sugg = models.IntegerField(
        blank=False,
        verbose_name="Répétitions recommandées"
    )

    description = models.CharField(
        max_length=400,
        blank=False,
        verbose_name="Description",
        validators=[MinLengthValidator(20), MaxLengthValidator(400)]
    )

    image = CloudinaryField('image', blank=True)

    est_approuve = models.BooleanField(default=False)

    class Meta:
        """Classe meta des exercices"""
        verbose_name = "Exercice"
        verbose_name_plural = "Exercices"
        ordering = ["nom", "groupe_musculaire"]

    def __str__(self):
        return f"{self.nom}"


class Entrainement(models.Model):
    """Modèle des entrainements"""

    nom = models.CharField(
        max_length=50,
        blank=False,
        verbose_name="Nom de l'entrainement",
    )

    date_creation = models.DateTimeField(
        default=timezone.now,
        verbose_name="Date de création"
    )


    exercices = models.ManyToManyField(
        Exercice,
        through="ExerciceEntrainement",
        verbose_name="Exercices",
        blank=True,
    )

    createur = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="proposed_exercices",
        verbose_name="Créateur",
        blank=True,
        default="",
        null=False
    )

    class Meta:
        """Classe meta des entrainements"""
        verbose_name = "Entrainement"
        verbose_name_plural = "Entrainements"
        ordering = ["nom"]

    def __str__(self):
        return f"{self.nom}"


class ExerciceEntrainement(models.Model):
    """Modèle des exercices et entrainements"""
    entrainement = models.ForeignKey(
        Entrainement,
        on_delete=models.CASCADE
    )

    exercice = models.ForeignKey(
        Exercice,
        on_delete=models.CASCADE
    )

    sets = models.PositiveIntegerField(
        blank=True,
        null=True,
        verbose_name="Sets personnalisés"
    )

    reps = models.PositiveIntegerField(
        blank=True,
        null=True,
        verbose_name="Répétitions personnalisées"
    )

    class Meta:
        """Classe meta des exercices et entrainements"""
        verbose_name = "Exercice dans l'entraînement"
        verbose_name_plural = "Exercices dans les entraînements"
        ordering = ['entrainement', 'exercice']
        unique_together = ('entrainement', 'exercice')

    def __str__(self):
        return f"{self.exercice} dans {self.entrainement}"

class Badge(models.Model):
    """Modèle des badges"""

    CATEGORIES = [
        ('FORCE', 'Force'),
        ('ENDURANCE', 'Endurance'),
        ('ASSIDUITE', 'Assiduité'),
        ('TECHNIQUE', 'Technique'),
        ('AUTRE', 'Autre'),
    ]

    STAT_CHOICES = [
        ('RÉPÉTITIONS', 'Répétitions totales'),
        ('SÉRIES', 'Séries totales'),
        ('EXERCICES', 'Exercices complétés'),
        ('ENTRAÎNEMENTS', 'Entraînements complétés'),
    ]

    nom = models.CharField(max_length=100)
    description = models.TextField()
    icone = CloudinaryField('image')
    categorie = models.CharField(
        max_length=50,
        choices=CATEGORIES,
        verbose_name="Catégorie du badge"
    )

    code = models.SlugField(
        unique=True,
        blank=True,
        null=False,
    )

    stat_cible = models.CharField(
        max_length=20,
        choices=STAT_CHOICES,
        verbose_name="Statistique ciblée pour ce badge",
    )

    seuil = models.PositiveIntegerField(
        verbose_name="Seuil à atteindre pour obtenir ce badge",
    )

    class Meta:
        ordering = ['nom']
        verbose_name = "Badge"
        verbose_name_plural = "Badges"

    def __str__(self):
        return f"{self.nom}"

    def save(self, *args, **kwargs):
        if not self.code and self.nom:
            self.code = slugify(self.nom)
        super().save(*args, **kwargs)



class Statistiques(models.Model):
    """Modèle des statistiques utilisateur"""

    user_id = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="statistiques",
        verbose_name="Utilisateur"
    )

    sets_effectues = models.PositiveIntegerField(
        default=0,
        verbose_name="Séries effectués"
    )

    reps_effectuees = models.PositiveIntegerField(
        default=0,
        verbose_name="Répétitions effectuées"
    )

    entrainements_completes = models.PositiveIntegerField(
        default=0,
        verbose_name="Entraînements complétés"
    )

    exercices_completes = models.PositiveIntegerField(
        default=0,
        verbose_name="Exercices complétés"
    )

    badges_obtenus = models.PositiveIntegerField(
        default=0,
        verbose_name="Badges obtenus"
    )

    class Meta:
        """Classe meta des statistiques"""
        verbose_name = "Statistique"
        verbose_name_plural = "Statistiques"
        ordering = ["exercices_completes"]

    def __str__(self):
        return f"Statistiques de {self.user_id.username}"

class Defis(models.Model):
    """Modèle des défis"""

    nom = models.CharField(
        max_length=100,
        blank=False,
        verbose_name="Nom du défi"
    )
    date_creation = models.DateTimeField(auto_now_add=True)
    date_limite = models.DateTimeField(
        verbose_name="Date limite de complétion",
    )

    badges = models.ManyToManyField(Badge, through="DefiBadge")

    class Meta:
        """Classe meta des défis"""
        verbose_name = "Défi"
        verbose_name_plural = "Défis"
        ordering =  ["nom"]

    def __str__(self):
        return f"Défi {self.nom}"

    def clean(self):
        if self.date_limite:
            if self.date_limite < timezone.now():
                raise ValidationError({
                    'date_limite': 'La date limite ne peux pas être passé'
                })

    def est_expire(self):
        """Retourne True si la date limite est dépassée."""
        return timezone.now() > self.date_limite

class DefiBadge(models.Model):
    defi = models.ForeignKey(Defis, on_delete=models.CASCADE)
    badge = models.ForeignKey('Badge', on_delete=models.CASCADE)

    class Meta:
        unique_together = ('defi', 'badge')

    def __str__(self):
        return f"{self.defi} - {self.badge}"

class UserBadgeProgress(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    badge = models.ForeignKey(Badge, on_delete=models.CASCADE)
    defi = models.ForeignKey(Defis, on_delete=models.CASCADE, null=False)
    est_complete = models.BooleanField(default=False)
    date_completion = models.DateTimeField(null=True, blank=True)

    class Meta:

site_web/templates/site_web/workouts/edit_workout.html
{% extends "site_web/base.html" %}
{% block title %}
    <title>RepXP | Modification d'entraînements</title>
{% endblock %} {% block navigation %}

<a href="{% url 'edit_workout' entrainement.id %}" class="active-link">MODIFICATION D'ENTRAÎNEMENTS</a>

{% endblock %} {% block main %}
    <form class="form-group background-form" method="post" novalidate>
        {% csrf_token %}
        <div class="mb-3 p-4">
            <div class="mb-3">
                <label for="{{ form.nom.id_for_label }}" class="form-label m-0 fw-semibold">Nom</label>
                {{ form.nom }}
                {% if form.nom.errors %}
                    <div class="invalid-feedback d-block">
                        {{ form.nom.errors.0 }}
                    </div>
                {% endif %}
            </div>

            <div class="row g-2 my-2">
                <div class="col-6">
                    <label for="{{ form.exercice_1.id_for_label }}" class="form-label m-0 fw-semibold">Exercice 1</label>
                    {{ form.exercice_1 }}
                    {% if form.exercice_1.errors %}
                        <div class="invalid-feedback d-block">
                            {{ form.exercice_1.errors.0 }}
                        </div>
                    {% endif %}
                </div>
                <div class="col-3">
                    <label for="{{ form.sets_1.id_for_label }}" class="form-label m-0 fw-semibold">Séries</label>
                    {{ form.sets_1 }}
                    {% if form.sets_1.errors %}
                        <div class="invalid-feedback d-block">
                            {{ form.sets_1.errors.0 }}
                        </div>
                    {% endif %}
                </div>
                <div class="col-3">
                    <label for="{{ form.reps_1.id_for_label }}" class="form-label m-0 fw-semibold">Répétitions</label>
                    {{ form.reps_1 }}
                    {% if form.reps_1.errors %}
                        <div class="invalid-feedback d-block">
                            {{ form.reps_1.errors.0 }}
                        </div>
                    {% endif %}
                </div>
            </div>

            <div class="row g-2 my-2">
                <div class="col-6">
                    <label for="{{ form.exercice_2.id_for_label }}" class="form-label m-0 fw-semibold">Exercice 2</label>
                    {{ form.exercice_2 }}
                    {% if form.exercice_2.errors %}
                        <div class="invalid-feedback d-block">
                            {{ form.exercice_2.errors.0 }}
                        </div>
                    {% endif %}
                </div>
                <div class="col-3">
                    <label for="{{ form.sets_2.id_for_label }}" class="form-label m-0 fw-semibold">Séries</label>
                    {{ form.sets_2 }}
                    {% if form.sets_2.errors %}
                        <div class="invalid-feedback d-block">
                            {{ form.sets_2.errors.0 }}
                        </div>
                    {% endif %}
                </div>
                <div class="col-3">
                    <label for="{{ form.reps_2.id_for_label }}" class="form-label m-0 fw-semibold">Répétitions</label>
                    {{ form.reps_2 }}
                    {% if form.reps_2.errors %}
                        <div class="invalid-feedback d-block">
                            {{ form.reps_2.errors.0 }}
                        </div>
                    {% endif %}
                </div>
            </div>
            <div class="row g-2 my-2">
                <div class="col-6">
                    <label for="{{ form.exercice_3.id_for_label }}" class="form-label m-0 fw-semibold">Exercice 3</label>
                    {{ form.exercice_3 }}
                    {% if form.exercice_3.errors %}
                        <div class="invalid-feedback d-block">
                            {{ form.exercice_3.errors.0 }}
                        </div>
                    {% endif %}
                </div>
                <div class="col-3">
                    <label for="{{ form.sets_3.id_for_label }}" class="form-label m-0 fw-semibold">Séries</label>
                    {{ form.sets_3 }}
                    {% if form.sets_3.errors %}
                        <div class="invalid-feedback d-block">
                            {{ form.sets_3.errors.0 }}
                        </div>
                    {% endif %}
                </div>
                <div class="col-3">
                    <label for="{{ form.reps_3.id_for_label }}" class="form-label m-0 fw-semibold">Répétitions</label>
                    {{ form.reps_3 }}
                    {% if form.reps_3.errors %}
                        <div class="invalid-feedback d-block">
                            {{ form.reps_3.errors.0 }}
                        </div>
                    {% endif %}
                </div>
            </div>
            <div class="row g-2 my-2">
                <div class="col-6">
                    <label for="{{ form.exercice_4.id_for_label }}" class="form-label m-0 fw-semibold">Exercice 4</label>
                    {{ form.exercice_4 }}
                    {% if form.exercice_4.errors %}
                        <div class="invalid-feedback d-block">
                            {{ form.exercice_4.errors.0 }}
                        </div>
                    {% endif %}
                </div>
                <div class="col-3">
                    <label for="{{ form.sets_4.id_for_label }}" class="form-label m-0 fw-semibold">Séries</label>
                    {{ form.sets_4 }}
                    {% if form.sets_4.errors %}
                        <div class="invalid-feedback d-block">
                            {{ form.sets_4.errors.0 }}
                        </div>
                    {% endif %}
                </div>
                <div class="col-3">
                    <label for="{{ form.reps_4.id_for_label }}" class="form-label m-0 fw-semibold">Répétitions</label>
                    {{ form.reps_4 }}
                    {% if form.reps_4.errors %}
                        <div class="invalid-feedback d-block">
                            {{ form.reps_4.errors.0 }}
                        </div>
                    {% endif %}
                </div>
            </div>

            <div class="d-flex justify-content-center">
                <input type="reset" class="form-control mt-3 style-button-danger w-50" value="RÉINITIALISER">
                <input type="submit" class="form-control mt-3 style-button w-50" value="MODIFIER">
            </div>
        </div>
    </form>
{% endblock %}

site_web/templates/site_web/workouts/my_workouts.html
{% extends "site_web/base.html" %}
{% block title %}
    <title>RepXP | Mes entraînements</title>
{% endblock %} {% block navigation %}

<a href="{% url 'my_workouts' %}" class="active-link">MES ENTRAÎNEMENTS</a>
<a href="{% url 'new_workout' %}" class="inactive-link">CRÉATION D'ENTRAÎNEMENTS</a>

{% endblock %} {% block main %}

<form method="get" class="my-3 pb-2 text-center d-flex justify-content-center">
    <input type="text" name="recherche" class="form-control w-25 me-3" placeholder="Rechercher un entrainement...">
    <button class="style-button" type="submit">RECHERCHER</button>
</form>

{% if entrainements %}
    <div class="accordion row justify-content-center" id="workoutsAccordion">
    {% for entrainement in entrainements %}
        <div class="col-8 accordion-item p-0 mx-auto">
            <h2 class="accordion-header">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ forloop.counter }}">
                    <img src="../../../static/images/dumbbells.png" alt="default" class="exercice-image me-2">
                    <strong class="text-blue">{{ entrainement.nom }}</strong>
                </button>
            </h2>
            <div id="collapse{{ forloop.counter }}" class="accordion-collapse collapse" data-bs-parent="#workoutsAccordion">
                <div class="accordion-body pe-2">
                    {% for exo_ent in entrainement.exerciceentrainement_set.all %}
                        {% if forloop.last %}
                            <div class="d-flex justify-content-between align-items-center">
                                <p class="mb-0"><a class="text-decoration-none" href="{% url 'bank' %}?recherche={{ exo_ent.exercice.nom }}">{{ exo_ent.exercice.nom }}</a> - {{ exo_ent.sets }} x {{ exo_ent.reps }}</p>
                                <div>
                                    <a href="#" data-bs-toggle="modal" data-bs-target="#completeModal{{ entrainement.id }}"><img src="../../../static/images/check.svg" alt="default" class="me-2 edit-img"></a>
                                    <a href="{% url 'edit_workout' entrainement.id %}"><img src="../../../static/images/edit.svg" alt="default" class="me-2 edit-img"></a>
                                    <a href="#" data-bs-toggle="modal" data-bs-target="#deleteModal{{ entrainement.id }}"><img src="../../../static/images/delete.svg" alt="default" class="edit-img"></a>
                                </div>
                            </div>
                        {% else %}
                            <div class="mb-2">
                                <p class="mb-0"><a class="text-decoration-none" href="{% url 'bank' %}?recherche={{ exo_ent.exercice.nom }}">{{ exo_ent.exercice.nom }}</a> - {{ exo_ent.sets }} x {{ exo_ent.reps }}</p>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>
        </div>

        <div class="modal fade" id="completeModal{{ entrainement.id }}" tabindex="-1" aria-labelledby="completeModalLabel{{ entrainement.id }}" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content text-center logout-popover">
                    <div class="modal-header border-0">
                        <h3 class="modal-title w-100 fw-bold" id="completeModalLabel{{ entrainement.id }}">Compléter l'entraînement</h3>
                    </div>
                    <div class="modal-body">
                        <div class="mb-4">
                            <h4 class="text-center">Avez-vous complété</h4>
                            <h4 class="text-center">l'entraînement "{{ entrainement.nom }}"?</h4>
                        </div>
                        <div class="d-flex justify-content-center">
                            <button type="button" class="style-button-danger" data-bs-dismiss="modal">ANNULER</button>
                            <form method="post" action="{% url 'complete_workout' entrainement.id %}">
                                {% csrf_token %}
                                <button type="submit" class="style-button">COMPLÉTER</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="modal fade" id="deleteModal{{ entrainement.id }}" tabindex="-1" aria-labelledby="deleteModalLabel{{ entrainement.id }}" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content text-center logout-popover">
                    <div class="modal-header border-0">
                        <h3 class="modal-title w-100 fw-bold" id="deleteModalLabel{{ entrainement.id }}">Confirmer la suppression</h3>
                    </div>
                    <div class="modal-body">
                        <div class="mb-4">
                            <h4 class="text-center">Voulez-vous vraiment supprimer</h4>
                            <h4 class="text-center">l'entraînement "{{ entrainement.nom }}"?</h4>
                        </div>
                        <div class="d-flex justify-content-center">
                            <button type="button" class="style-button-danger" data-bs-dismiss="modal">ANNULER</button>
                            <form method="post" action="{% url 'delete_workout' entrainement.id %}">
                                {% csrf_token %}
                                <button type="submit" class="style-button">SUPPRIMER</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>
{% else %}
    <p class="text-center">Aucun entrainement enregistré pour l'instant.</p>
{% endif %}

{% endblock %}